// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.

// Define UI translation keys.
export class UITranslationKey
{
    // Mod title and description.
    public static Title                                             : string = "BuildingUse.Title";
    public static Description                                       : string = "BuildingUse.Description";

    // Infoview titles.
    public static InfoviewTitleEmployees                            : string = "Infoviews.INFOVIEW[BuildingUseEmployees]";
    public static InfoviewTitleVisitors                             : string = "Infoviews.INFOVIEW[BuildingUseVisitors]";
    public static InfoviewTitleStorage                              : string = "Infoviews.INFOVIEW[BuildingUseStorage]";
    public static InfoviewTitleVehicles                             : string = "Infoviews.INFOVIEW[BuildingUseVehicles]";
    public static InfoviewTitleEfficiency                           : string = "Infoviews.INFOVIEW[BuildingUseEfficiency]";
    public static InfoviewTitleProcessing                           : string = "Infoviews.INFOVIEW[BuildingUseProcessing]";

    // Infomode titles.
    public static InfomodeTitleEmployeesResidential                 : string = "Infoviews.INFOMODE[BuildingUseEmployeesResidential]";
    public static InfomodeTitleEmployeesCommercial                  : string = "Infoviews.INFOMODE[BuildingUseEmployeesCommercial]";
    public static InfomodeTitleEmployeesIndustrial                  : string = "Infoviews.INFOMODE[BuildingUseEmployeesIndustrial]";
    public static InfomodeTitleEmployeesOffice                      : string = "Infoviews.INFOMODE[BuildingUseEmployeesOffice]";
    public static InfomodeTitleEmployeesParking                     : string = "Infoviews.INFOMODE[BuildingUseEmployeesParking]";
    public static InfomodeTitleEmployeesRoadMaintenance             : string = "Infoviews.INFOMODE[BuildingUseEmployeesRoadMaintenance]";
    public static InfomodeTitleEmployeesElectricity                 : string = "Infoviews.INFOMODE[BuildingUseEmployeesElectricity]";
    public static InfomodeTitleEmployeesWater                       : string = "Infoviews.INFOMODE[BuildingUseEmployeesWater]";
    public static InfomodeTitleEmployeesSewage                      : string = "Infoviews.INFOMODE[BuildingUseEmployeesSewage]";
    public static InfomodeTitleEmployeesHealthcare                  : string = "Infoviews.INFOMODE[BuildingUseEmployeesHealthcare]";
    public static InfomodeTitleEmployeesDeathcare                   : string = "Infoviews.INFOMODE[BuildingUseEmployeesDeathcare]";
    public static InfomodeTitleEmployeesGarbageManagement           : string = "Infoviews.INFOMODE[BuildingUseEmployeesGarbageManagement]";
    public static InfomodeTitleEmployeesEducation                   : string = "Infoviews.INFOMODE[BuildingUseEmployeesEducation]";
    public static InfomodeTitleEmployeesResearch                    : string = "Infoviews.INFOMODE[BuildingUseEmployeesResearch]";
    public static InfomodeTitleEmployeesFireRescue                  : string = "Infoviews.INFOMODE[BuildingUseEmployeesFireRescue]";
    public static InfomodeTitleEmployeesDisasterControl             : string = "Infoviews.INFOMODE[BuildingUseEmployeesDisasterControl]";
    public static InfomodeTitleEmployeesPolice                      : string = "Infoviews.INFOMODE[BuildingUseEmployeesPolice]";
    public static InfomodeTitleEmployeesAdministration              : string = "Infoviews.INFOMODE[BuildingUseEmployeesAdministration]";
    public static InfomodeTitleEmployeesTransportation              : string = "Infoviews.INFOMODE[BuildingUseEmployeesTransportation]";
    public static InfomodeTitleEmployeesParkMaintenance             : string = "Infoviews.INFOMODE[BuildingUseEmployeesParkMaintenance]";
    public static InfomodeTitleEmployeesParksRecreation             : string = "Infoviews.INFOMODE[BuildingUseEmployeesParksRecreation]";
    public static InfomodeTitleEmployeesPost                        : string = "Infoviews.INFOMODE[BuildingUseEmployeesPost]";
    public static InfomodeTitleEmployeesTelecom                     : string = "Infoviews.INFOMODE[BuildingUseEmployeesTelecom]";
    public static InfomodeTitleVisitorsHealthcare                   : string = "Infoviews.INFOMODE[BuildingUseVisitorsHealthcare]";
    public static InfomodeTitleVisitorsCemetery                     : string = "Infoviews.INFOMODE[BuildingUseVisitorsCemetery]";
    public static InfomodeTitleVisitorsCrematorium                  : string = "Infoviews.INFOMODE[BuildingUseVisitorsCrematorium]";
    public static InfomodeTitleVisitorsElementarySchool             : string = "Infoviews.INFOMODE[BuildingUseVisitorsElementarySchool]";
    public static InfomodeTitleVisitorsHighSchool                   : string = "Infoviews.INFOMODE[BuildingUseVisitorsHighSchool]";
    public static InfomodeTitleVisitorsCollege                      : string = "Infoviews.INFOMODE[BuildingUseVisitorsCollege]";
    public static InfomodeTitleVisitorsUniversity                   : string = "Infoviews.INFOMODE[BuildingUseVisitorsUniversity]";
    public static InfomodeTitleVisitorsEmergencyShelter             : string = "Infoviews.INFOMODE[BuildingUseVisitorsEmergencyShelter]";
    public static InfomodeTitleVisitorsPoliceStation                : string = "Infoviews.INFOMODE[BuildingUseVisitorsPoliceStation]";
    public static InfomodeTitleVisitorsPrison                       : string = "Infoviews.INFOMODE[BuildingUseVisitorsPrison]";
    public static InfomodeTitleStorageCommercial                    : string = "Infoviews.INFOMODE[BuildingUseStorageCommercial]";
    public static InfomodeTitleStorageIndustrial                    : string = "Infoviews.INFOMODE[BuildingUseStorageIndustrial]";
    public static InfomodeTitleStorageOffice                        : string = "Infoviews.INFOMODE[BuildingUseStorageOffice]";
    public static InfomodeTitleStorageBatteryCharge                 : string = "Infoviews.INFOMODE[BuildingUseStorageBatteryCharge]";
    public static InfomodeTitleStoragePowerPlantFuel                : string = "Infoviews.INFOMODE[BuildingUseStoragePowerPlantFuel]";
    public static InfomodeTitleStorageHealthcare                    : string = "Infoviews.INFOMODE[BuildingUseStorageHealthcare]";
    public static InfomodeTitleStorageLandfill                      : string = "Infoviews.INFOMODE[BuildingUseStorageLandfill]";
    public static InfomodeTitleStorageGarbageManagement             : string = "Infoviews.INFOMODE[BuildingUseStorageGarbageManagement]";
    public static InfomodeTitleStorageEmergencyShelter              : string = "Infoviews.INFOMODE[BuildingUseStorageEmergencyShelter]";
    public static InfomodeTitleStorageCargoTransportation           : string = "Infoviews.INFOMODE[BuildingUseStorageCargoTransportation]";
    public static InfomodeTitleStoragePost                          : string = "Infoviews.INFOMODE[BuildingUseStoragePost]";
    public static InfomodeTitleVehiclesCommercialTruck              : string = "Infoviews.INFOMODE[BuildingUseVehiclesCommercialTruck]";
    public static InfomodeTitleVehiclesIndustrialTruck              : string = "Infoviews.INFOMODE[BuildingUseVehiclesIndustrialTruck]";
    public static InfomodeTitleVehiclesOfficeTruck                  : string = "Infoviews.INFOMODE[BuildingUseVehiclesOfficeTruck]";
    public static InfomodeTitleVehiclesParked                       : string = "Infoviews.INFOMODE[BuildingUseVehiclesParked]";
    public static InfomodeTitleVehiclesRoadMaintenance              : string = "Infoviews.INFOMODE[BuildingUseVehiclesRoadMaintenance]";
    public static InfomodeTitleVehiclesAmbulance                    : string = "Infoviews.INFOMODE[BuildingUseVehiclesAmbulance]";
    public static InfomodeTitleVehiclesMedicalHelicopter            : string = "Infoviews.INFOMODE[BuildingUseVehiclesMedicalHelicopter]";
    public static InfomodeTitleVehiclesHearse                       : string = "Infoviews.INFOMODE[BuildingUseVehiclesHearse]";
    public static InfomodeTitleVehiclesGarbageTruck                 : string = "Infoviews.INFOMODE[BuildingUseVehiclesGarbageTruck]";
    public static InfomodeTitleVehiclesFireEngine                   : string = "Infoviews.INFOMODE[BuildingUseVehiclesFireEngine]";
    public static InfomodeTitleVehiclesFireHelicopter               : string = "Infoviews.INFOMODE[BuildingUseVehiclesFireHelicopter]";
    public static InfomodeTitleVehiclesDisasterResponse             : string = "Infoviews.INFOMODE[BuildingUseVehiclesDisasterResponse]";
    public static InfomodeTitleVehiclesEvacuationBus                : string = "Infoviews.INFOMODE[BuildingUseVehiclesEvacuationBus]";
    public static InfomodeTitleVehiclesPoliceCar                    : string = "Infoviews.INFOMODE[BuildingUseVehiclesPoliceCar]";
    public static InfomodeTitleVehiclesPoliceHelicopter             : string = "Infoviews.INFOMODE[BuildingUseVehiclesPoliceHelicopter]";
    public static InfomodeTitleVehiclesPrisonVan                    : string = "Infoviews.INFOMODE[BuildingUseVehiclesPrisonVan]";
    public static InfomodeTitleVehiclesBus                          : string = "Infoviews.INFOMODE[BuildingUseVehiclesBus]";
    public static InfomodeTitleVehiclesTaxi                         : string = "Infoviews.INFOMODE[BuildingUseVehiclesTaxi]";
    public static InfomodeTitleVehiclesTrain                        : string = "Infoviews.INFOMODE[BuildingUseVehiclesTrain]";
    public static InfomodeTitleVehiclesTram                         : string = "Infoviews.INFOMODE[BuildingUseVehiclesTram]";
    public static InfomodeTitleVehiclesSubway                       : string = "Infoviews.INFOMODE[BuildingUseVehiclesSubway]";
    public static InfomodeTitleVehiclesParkMaintenance              : string = "Infoviews.INFOMODE[BuildingUseVehiclesParkMaintenance]";
    public static InfomodeTitleVehiclesPost                         : string = "Infoviews.INFOMODE[BuildingUseVehiclesPost]";
    public static InfomodeTitleVehiclesCargoStationTruck            : string = "Infoviews.INFOMODE[BuildingUseVehiclesCargoStationTruck]";
    public static InfomodeTitleEfficiencyCommercial                 : string = "Infoviews.INFOMODE[BuildingUseEfficiencyCommercial]";
    public static InfomodeTitleEfficiencyIndustrial                 : string = "Infoviews.INFOMODE[BuildingUseEfficiencyIndustrial]";
    public static InfomodeTitleEfficiencyOffice                     : string = "Infoviews.INFOMODE[BuildingUseEfficiencyOffice]";
    public static InfomodeTitleEfficiencyParking                    : string = "Infoviews.INFOMODE[BuildingUseEfficiencyParking]";
    public static InfomodeTitleEfficiencyRoadMaintenance            : string = "Infoviews.INFOMODE[BuildingUseEfficiencyRoadMaintenance]";
    public static InfomodeTitleEfficiencyElectricity                : string = "Infoviews.INFOMODE[BuildingUseEfficiencyElectricity]";
    public static InfomodeTitleEfficiencyWater                      : string = "Infoviews.INFOMODE[BuildingUseEfficiencyWater]";
    public static InfomodeTitleEfficiencySewage                     : string = "Infoviews.INFOMODE[BuildingUseEfficiencySewage]";
    public static InfomodeTitleEfficiencyHealthcare                 : string = "Infoviews.INFOMODE[BuildingUseEfficiencyHealthcare]";
    public static InfomodeTitleEfficiencyDeathcare                  : string = "Infoviews.INFOMODE[BuildingUseEfficiencyDeathcare]";
    public static InfomodeTitleEfficiencyGarbageManagement          : string = "Infoviews.INFOMODE[BuildingUseEfficiencyGarbageManagement]";
    public static InfomodeTitleEfficiencyEducation                  : string = "Infoviews.INFOMODE[BuildingUseEfficiencyEducation]";
    public static InfomodeTitleEfficiencyResearch                   : string = "Infoviews.INFOMODE[BuildingUseEfficiencyResearch]";
    public static InfomodeTitleEfficiencyFireRescue                 : string = "Infoviews.INFOMODE[BuildingUseEfficiencyFireRescue]";
    public static InfomodeTitleEfficiencyDisasterControl            : string = "Infoviews.INFOMODE[BuildingUseEfficiencyDisasterControl]";
    public static InfomodeTitleEfficiencyPolice                     : string = "Infoviews.INFOMODE[BuildingUseEfficiencyPolice]";
    public static InfomodeTitleEfficiencyAdministration             : string = "Infoviews.INFOMODE[BuildingUseEfficiencyAdministration]";
    public static InfomodeTitleEfficiencyTransportation             : string = "Infoviews.INFOMODE[BuildingUseEfficiencyTransportation]";
    public static InfomodeTitleEfficiencyParkMaintenance            : string = "Infoviews.INFOMODE[BuildingUseEfficiencyParkMaintenance]";
    public static InfomodeTitleEfficiencyParksRecreation            : string = "Infoviews.INFOMODE[BuildingUseEfficiencyParksRecreation]";
    public static InfomodeTitleEfficiencyPost                       : string = "Infoviews.INFOMODE[BuildingUseEfficiencyPost]";
    public static InfomodeTitleEfficiencyTelecom                    : string = "Infoviews.INFOMODE[BuildingUseEfficiencyTelecom]";
    public static InfomodeTitleProcessingElectricityProduction      : string = "Infoviews.INFOMODE[BuildingUseProcessingElectricityProduction]";
    public static InfomodeTitleProcessingWaterOutput                : string = "Infoviews.INFOMODE[BuildingUseProcessingWaterOutput]";
    public static InfomodeTitleProcessingSewageTreatment            : string = "Infoviews.INFOMODE[BuildingUseProcessingSewageTreatment]";
    public static InfomodeTitleProcessingCrematoriumProcessing      : string = "Infoviews.INFOMODE[BuildingUseProcessingCrematoriumProcessing]";
    public static InfomodeTitleProcessingGarbageProcessing          : string = "Infoviews.INFOMODE[BuildingUseProcessingGarbageProcessing]";
    public static InfomodeTitleProcessingMailSortingSpeed           : string = "Infoviews.INFOMODE[BuildingUseProcessingMailSortingSpeed]";

    // Infomode tooltips.
    public static InfomodeTooltipEmployeesResidential               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesResidential]";
    public static InfomodeTooltipEmployeesCommercial                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesCommercial]";
    public static InfomodeTooltipEmployeesIndustrial                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesIndustrial]";
    public static InfomodeTooltipEmployeesOffice                    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesOffice]";
    public static InfomodeTooltipEmployeesParking                   : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesParking]";
    public static InfomodeTooltipEmployeesRoadMaintenance           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesRoadMaintenance]";
    public static InfomodeTooltipEmployeesElectricity               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesElectricity]";
    public static InfomodeTooltipEmployeesWater                     : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesWater]";
    public static InfomodeTooltipEmployeesSewage                    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesSewage]";
    public static InfomodeTooltipEmployeesHealthcare                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesHealthcare]";
    public static InfomodeTooltipEmployeesDeathcare                 : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesDeathcare]";
    public static InfomodeTooltipEmployeesGarbageManagement         : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesGarbageManagement]";
    public static InfomodeTooltipEmployeesEducation                 : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesEducation]";
    public static InfomodeTooltipEmployeesResearch                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesResearch]";
    public static InfomodeTooltipEmployeesFireRescue                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesFireRescue]";
    public static InfomodeTooltipEmployeesDisasterControl           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesDisasterControl]";
    public static InfomodeTooltipEmployeesPolice                    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesPolice]";
    public static InfomodeTooltipEmployeesAdministration            : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesAdministration]";
    public static InfomodeTooltipEmployeesTransportation            : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesTransportation]";
    public static InfomodeTooltipEmployeesParkMaintenance           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesParkMaintenance]";
    public static InfomodeTooltipEmployeesParksRecreation           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesParksRecreation]";
    public static InfomodeTooltipEmployeesPost                      : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesPost]";
    public static InfomodeTooltipEmployeesTelecom                   : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesTelecom]";
    public static InfomodeTooltipVisitorsHealthcare                 : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsHealthcare]";
    public static InfomodeTooltipVisitorsCemetery                   : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsCemetery]";
    public static InfomodeTooltipVisitorsCrematorium                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsCrematorium]";
    public static InfomodeTooltipVisitorsElementarySchool           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsElementarySchool]";
    public static InfomodeTooltipVisitorsHighSchool                 : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsHighSchool]";
    public static InfomodeTooltipVisitorsCollege                    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsCollege]";
    public static InfomodeTooltipVisitorsUniversity                 : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsUniversity]";
    public static InfomodeTooltipVisitorsEmergencyShelter           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsEmergencyShelter]";
    public static InfomodeTooltipVisitorsPoliceStation              : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsPoliceStation]";
    public static InfomodeTooltipVisitorsPrison                     : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsPrison]";
    public static InfomodeTooltipStorageCommercial                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageCommercial]";
    public static InfomodeTooltipStorageIndustrial                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageIndustrial]";
    public static InfomodeTooltipStorageOffice                      : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageOffice]";
    public static InfomodeTooltipStorageBatteryCharge               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageBatteryCharge]";
    public static InfomodeTooltipStoragePowerPlantFuel              : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStoragePowerPlantFuel]";
    public static InfomodeTooltipStorageHealthcare                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageHealthcare]";
    public static InfomodeTooltipStorageLandfill                    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageLandfill]";
    public static InfomodeTooltipStorageGarbageManagement           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageGarbageManagement]";
    public static InfomodeTooltipStorageEmergencyShelter            : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageEmergencyShelter]";
    public static InfomodeTooltipStorageCargoTransportation         : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageCargoTransportation]";
    public static InfomodeTooltipStoragePost                        : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStoragePost]";
    public static InfomodeTooltipVehiclesCommercialTruck            : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesCommercialTruck]";
    public static InfomodeTooltipVehiclesIndustrialTruck            : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesIndustrialTruck]";
    public static InfomodeTooltipVehiclesOfficeTruck                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesOfficeTruck]";
    public static InfomodeTooltipVehiclesParked                     : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesParked]";
    public static InfomodeTooltipVehiclesRoadMaintenance            : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesRoadMaintenance]";
    public static InfomodeTooltipVehiclesAmbulance                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesAmbulance]";
    public static InfomodeTooltipVehiclesMedicalHelicopter          : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesMedicalHelicopter]";
    public static InfomodeTooltipVehiclesHearse                     : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesHearse]";
    public static InfomodeTooltipVehiclesGarbageTruck               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesGarbageTruck]";
    public static InfomodeTooltipVehiclesFireEngine                 : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesFireEngine]";
    public static InfomodeTooltipVehiclesFireHelicopter             : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesFireHelicopter]";
    public static InfomodeTooltipVehiclesDisasterResponse           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesDisasterResponse]";
    public static InfomodeTooltipVehiclesEvacuationBus              : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesEvacuationBus]";
    public static InfomodeTooltipVehiclesPoliceCar                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPoliceCar]";
    public static InfomodeTooltipVehiclesPoliceHelicopter           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPoliceHelicopter]";
    public static InfomodeTooltipVehiclesPrisonVan                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPrisonVan]";
    public static InfomodeTooltipVehiclesBus                        : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesBus]";
    public static InfomodeTooltipVehiclesTaxi                       : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesTaxi]";
    public static InfomodeTooltipVehiclesTrain                      : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesTrain]";
    public static InfomodeTooltipVehiclesTram                       : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesTram]";
    public static InfomodeTooltipVehiclesSubway                     : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesSubway]";
    public static InfomodeTooltipVehiclesParkMaintenance            : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesParkMaintenance]";
    public static InfomodeTooltipVehiclesPost                       : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPost]";
    public static InfomodeTooltipVehiclesCargoStationTruck          : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesCargoStationTruck]";
    public static InfomodeTooltipEfficiencyCommercial               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyCommercial]";
    public static InfomodeTooltipEfficiencyIndustrial               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyIndustrial]";
    public static InfomodeTooltipEfficiencyOffice                   : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyOffice]";
    public static InfomodeTooltipEfficiencyParking                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyParking]";
    public static InfomodeTooltipEfficiencyRoadMaintenance          : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyRoadMaintenance]";
    public static InfomodeTooltipEfficiencyElectricity              : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyElectricity]";
    public static InfomodeTooltipEfficiencyWater                    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyWater]";
    public static InfomodeTooltipEfficiencySewage                   : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencySewage]";
    public static InfomodeTooltipEfficiencyHealthcare               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyHealthcare]";
    public static InfomodeTooltipEfficiencyDeathcare                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyDeathcare]";
    public static InfomodeTooltipEfficiencyGarbageManagement        : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyGarbageManagement]";
    public static InfomodeTooltipEfficiencyEducation                : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyEducation]";
    public static InfomodeTooltipEfficiencyResearch                 : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyResearch]";
    public static InfomodeTooltipEfficiencyFireRescue               : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyFireRescue]";
    public static InfomodeTooltipEfficiencyDisasterControl          : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyDisasterControl]";
    public static InfomodeTooltipEfficiencyPolice                   : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyPolice]";
    public static InfomodeTooltipEfficiencyAdministration           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyAdministration]";
    public static InfomodeTooltipEfficiencyTransportation           : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyTransportation]";
    public static InfomodeTooltipEfficiencyParkMaintenance          : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyParkMaintenance]";
    public static InfomodeTooltipEfficiencyParksRecreation          : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyParksRecreation]";
    public static InfomodeTooltipEfficiencyPost                     : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyPost]";
    public static InfomodeTooltipEfficiencyTelecom                  : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyTelecom]";
    public static InfomodeTooltipProcessingElectricityProduction    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingElectricityProduction]";
    public static InfomodeTooltipProcessingWaterOutput              : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingWaterOutput]";
    public static InfomodeTooltipProcessingSewageTreatment          : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingSewageTreatment]";
    public static InfomodeTooltipProcessingCrematoriumProcessing    : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingCrematoriumProcessing]";
    public static InfomodeTooltipProcessingGarbageProcessing        : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingGarbageProcessing]";
    public static InfomodeTooltipProcessingMailSortingSpeed         : string = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingMailSortingSpeed]";

    // District selector text.
    public static EntireCity                                        : string = "BuildingUse.EntireCity";
    public static DistrictSelectorTooltip                           : string = "BuildingUse.DistrictSelectorTooltip";

    // Select/deselect text.
    public static SelectAll                                         : string = "BuildingUse.SelectAll";
    public static DeselectAll                                       : string = "BuildingUse.DeselectAll";
    public static SelectDeselectTooltip                             : string = "BuildingUse.SelectDeselectTooltip";

    // Vehicles in use/in maintenance text.
    public static InUse                                             : string = "BuildingUse.InUse";
    public static InMaintenance                                     : string = "BuildingUse.InMaintenance";
    public static InUseInMaintenanceTooltip                         : string = "BuildingUse.InUseInMaintenanceTooltip";

    // Max color text.
    public static MaxColor100Percent                                : string = "BuildingUse.MaxColor100Percent";
    public static MaxColor200Percent                                : string = "BuildingUse.MaxColor200Percent";
    public static MaxColorTooltip                                   : string = "BuildingUse.MaxColorTooltip";

    // Unit of measure text.
    public static UnitOfMeasurePrefixKilo                           : string = "BuildingUse.UnitOfMeasurePrefixKilo";
    public static UnitOfMeasurePrefixMega                           : string = "BuildingUse.UnitOfMeasurePrefixMega";
    public static GigaWattHour                                      : string = "BuildingUse.GigaWattHour";

    // General text.
    public static NoBuildings                                       : string = "BuildingUse.NoBuildings";
}
