// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class CreateUIFiles.
// Make any needed changes in class CreateUIFiles.

namespace BuildingUse
{
    // Define UI translation keys.
    public class UITranslationKey
    {
        // Mod title and description.
        public const string Title                                              = "BuildingUse.Title";
        public const string Description                                        = "BuildingUse.Description";

        // Infoview titles.
        public const string InfoviewTitleEmployees                             = "Infoviews.INFOVIEW[BuildingUseEmployees]";
        public const string InfoviewTitleVisitors                              = "Infoviews.INFOVIEW[BuildingUseVisitors]";
        public const string InfoviewTitleStorage                               = "Infoviews.INFOVIEW[BuildingUseStorage]";
        public const string InfoviewTitleVehicles                              = "Infoviews.INFOVIEW[BuildingUseVehicles]";
        public const string InfoviewTitleEfficiency                            = "Infoviews.INFOVIEW[BuildingUseEfficiency]";
        public const string InfoviewTitleProcessing                            = "Infoviews.INFOVIEW[BuildingUseProcessing]";

        // Infomode titles.
        public const string InfomodeTitleEmployeesResidential                  = "Infoviews.INFOMODE[BuildingUseEmployeesResidential]";
        public const string InfomodeTitleEmployeesCommercial                   = "Infoviews.INFOMODE[BuildingUseEmployeesCommercial]";
        public const string InfomodeTitleEmployeesIndustrial                   = "Infoviews.INFOMODE[BuildingUseEmployeesIndustrial]";
        public const string InfomodeTitleEmployeesOffice                       = "Infoviews.INFOMODE[BuildingUseEmployeesOffice]";
        public const string InfomodeTitleEmployeesParking                      = "Infoviews.INFOMODE[BuildingUseEmployeesParking]";
        public const string InfomodeTitleEmployeesRoadMaintenance              = "Infoviews.INFOMODE[BuildingUseEmployeesRoadMaintenance]";
        public const string InfomodeTitleEmployeesElectricity                  = "Infoviews.INFOMODE[BuildingUseEmployeesElectricity]";
        public const string InfomodeTitleEmployeesWater                        = "Infoviews.INFOMODE[BuildingUseEmployeesWater]";
        public const string InfomodeTitleEmployeesSewage                       = "Infoviews.INFOMODE[BuildingUseEmployeesSewage]";
        public const string InfomodeTitleEmployeesHealthcare                   = "Infoviews.INFOMODE[BuildingUseEmployeesHealthcare]";
        public const string InfomodeTitleEmployeesDeathcare                    = "Infoviews.INFOMODE[BuildingUseEmployeesDeathcare]";
        public const string InfomodeTitleEmployeesGarbageManagement            = "Infoviews.INFOMODE[BuildingUseEmployeesGarbageManagement]";
        public const string InfomodeTitleEmployeesEducation                    = "Infoviews.INFOMODE[BuildingUseEmployeesEducation]";
        public const string InfomodeTitleEmployeesResearch                     = "Infoviews.INFOMODE[BuildingUseEmployeesResearch]";
        public const string InfomodeTitleEmployeesFireRescue                   = "Infoviews.INFOMODE[BuildingUseEmployeesFireRescue]";
        public const string InfomodeTitleEmployeesDisasterControl              = "Infoviews.INFOMODE[BuildingUseEmployeesDisasterControl]";
        public const string InfomodeTitleEmployeesPolice                       = "Infoviews.INFOMODE[BuildingUseEmployeesPolice]";
        public const string InfomodeTitleEmployeesAdministration               = "Infoviews.INFOMODE[BuildingUseEmployeesAdministration]";
        public const string InfomodeTitleEmployeesTransportation               = "Infoviews.INFOMODE[BuildingUseEmployeesTransportation]";
        public const string InfomodeTitleEmployeesParkMaintenance              = "Infoviews.INFOMODE[BuildingUseEmployeesParkMaintenance]";
        public const string InfomodeTitleEmployeesParksRecreation              = "Infoviews.INFOMODE[BuildingUseEmployeesParksRecreation]";
        public const string InfomodeTitleEmployeesPost                         = "Infoviews.INFOMODE[BuildingUseEmployeesPost]";
        public const string InfomodeTitleEmployeesTelecom                      = "Infoviews.INFOMODE[BuildingUseEmployeesTelecom]";
        public const string InfomodeTitleVisitorsHealthcare                    = "Infoviews.INFOMODE[BuildingUseVisitorsHealthcare]";
        public const string InfomodeTitleVisitorsCemetery                      = "Infoviews.INFOMODE[BuildingUseVisitorsCemetery]";
        public const string InfomodeTitleVisitorsCrematorium                   = "Infoviews.INFOMODE[BuildingUseVisitorsCrematorium]";
        public const string InfomodeTitleVisitorsElementarySchool              = "Infoviews.INFOMODE[BuildingUseVisitorsElementarySchool]";
        public const string InfomodeTitleVisitorsHighSchool                    = "Infoviews.INFOMODE[BuildingUseVisitorsHighSchool]";
        public const string InfomodeTitleVisitorsCollege                       = "Infoviews.INFOMODE[BuildingUseVisitorsCollege]";
        public const string InfomodeTitleVisitorsUniversity                    = "Infoviews.INFOMODE[BuildingUseVisitorsUniversity]";
        public const string InfomodeTitleVisitorsEmergencyShelter              = "Infoviews.INFOMODE[BuildingUseVisitorsEmergencyShelter]";
        public const string InfomodeTitleVisitorsPoliceStation                 = "Infoviews.INFOMODE[BuildingUseVisitorsPoliceStation]";
        public const string InfomodeTitleVisitorsPrison                        = "Infoviews.INFOMODE[BuildingUseVisitorsPrison]";
        public const string InfomodeTitleStorageCommercial                     = "Infoviews.INFOMODE[BuildingUseStorageCommercial]";
        public const string InfomodeTitleStorageIndustrial                     = "Infoviews.INFOMODE[BuildingUseStorageIndustrial]";
        public const string InfomodeTitleStorageOffice                         = "Infoviews.INFOMODE[BuildingUseStorageOffice]";
        public const string InfomodeTitleStorageBatteryCharge                  = "Infoviews.INFOMODE[BuildingUseStorageBatteryCharge]";
        public const string InfomodeTitleStoragePowerPlantFuel                 = "Infoviews.INFOMODE[BuildingUseStoragePowerPlantFuel]";
        public const string InfomodeTitleStorageHealthcare                     = "Infoviews.INFOMODE[BuildingUseStorageHealthcare]";
        public const string InfomodeTitleStorageLandfill                       = "Infoviews.INFOMODE[BuildingUseStorageLandfill]";
        public const string InfomodeTitleStorageGarbageManagement              = "Infoviews.INFOMODE[BuildingUseStorageGarbageManagement]";
        public const string InfomodeTitleStorageEmergencyShelter               = "Infoviews.INFOMODE[BuildingUseStorageEmergencyShelter]";
        public const string InfomodeTitleStorageCargoTransportation            = "Infoviews.INFOMODE[BuildingUseStorageCargoTransportation]";
        public const string InfomodeTitleStoragePost                           = "Infoviews.INFOMODE[BuildingUseStoragePost]";
        public const string InfomodeTitleVehiclesCommercialTruck               = "Infoviews.INFOMODE[BuildingUseVehiclesCommercialTruck]";
        public const string InfomodeTitleVehiclesIndustrialTruck               = "Infoviews.INFOMODE[BuildingUseVehiclesIndustrialTruck]";
        public const string InfomodeTitleVehiclesOfficeTruck                   = "Infoviews.INFOMODE[BuildingUseVehiclesOfficeTruck]";
        public const string InfomodeTitleVehiclesParked                        = "Infoviews.INFOMODE[BuildingUseVehiclesParked]";
        public const string InfomodeTitleVehiclesRoadMaintenance               = "Infoviews.INFOMODE[BuildingUseVehiclesRoadMaintenance]";
        public const string InfomodeTitleVehiclesAmbulance                     = "Infoviews.INFOMODE[BuildingUseVehiclesAmbulance]";
        public const string InfomodeTitleVehiclesMedicalHelicopter             = "Infoviews.INFOMODE[BuildingUseVehiclesMedicalHelicopter]";
        public const string InfomodeTitleVehiclesHearse                        = "Infoviews.INFOMODE[BuildingUseVehiclesHearse]";
        public const string InfomodeTitleVehiclesGarbageTruck                  = "Infoviews.INFOMODE[BuildingUseVehiclesGarbageTruck]";
        public const string InfomodeTitleVehiclesFireEngine                    = "Infoviews.INFOMODE[BuildingUseVehiclesFireEngine]";
        public const string InfomodeTitleVehiclesFireHelicopter                = "Infoviews.INFOMODE[BuildingUseVehiclesFireHelicopter]";
        public const string InfomodeTitleVehiclesDisasterResponse              = "Infoviews.INFOMODE[BuildingUseVehiclesDisasterResponse]";
        public const string InfomodeTitleVehiclesEvacuationBus                 = "Infoviews.INFOMODE[BuildingUseVehiclesEvacuationBus]";
        public const string InfomodeTitleVehiclesPoliceCar                     = "Infoviews.INFOMODE[BuildingUseVehiclesPoliceCar]";
        public const string InfomodeTitleVehiclesPoliceHelicopter              = "Infoviews.INFOMODE[BuildingUseVehiclesPoliceHelicopter]";
        public const string InfomodeTitleVehiclesPrisonVan                     = "Infoviews.INFOMODE[BuildingUseVehiclesPrisonVan]";
        public const string InfomodeTitleVehiclesBus                           = "Infoviews.INFOMODE[BuildingUseVehiclesBus]";
        public const string InfomodeTitleVehiclesTaxi                          = "Infoviews.INFOMODE[BuildingUseVehiclesTaxi]";
        public const string InfomodeTitleVehiclesTrain                         = "Infoviews.INFOMODE[BuildingUseVehiclesTrain]";
        public const string InfomodeTitleVehiclesTram                          = "Infoviews.INFOMODE[BuildingUseVehiclesTram]";
        public const string InfomodeTitleVehiclesSubway                        = "Infoviews.INFOMODE[BuildingUseVehiclesSubway]";
        public const string InfomodeTitleVehiclesParkMaintenance               = "Infoviews.INFOMODE[BuildingUseVehiclesParkMaintenance]";
        public const string InfomodeTitleVehiclesPost                          = "Infoviews.INFOMODE[BuildingUseVehiclesPost]";
        public const string InfomodeTitleVehiclesCargoStationTruck             = "Infoviews.INFOMODE[BuildingUseVehiclesCargoStationTruck]";
        public const string InfomodeTitleEfficiencyResidential                 = "Infoviews.INFOMODE[BuildingUseEfficiencyResidential]";
        public const string InfomodeTitleEfficiencyCommercial                  = "Infoviews.INFOMODE[BuildingUseEfficiencyCommercial]";
        public const string InfomodeTitleEfficiencyIndustrial                  = "Infoviews.INFOMODE[BuildingUseEfficiencyIndustrial]";
        public const string InfomodeTitleEfficiencyOffice                      = "Infoviews.INFOMODE[BuildingUseEfficiencyOffice]";
        public const string InfomodeTitleEfficiencyParking                     = "Infoviews.INFOMODE[BuildingUseEfficiencyParking]";
        public const string InfomodeTitleEfficiencyRoadMaintenance             = "Infoviews.INFOMODE[BuildingUseEfficiencyRoadMaintenance]";
        public const string InfomodeTitleEfficiencyElectricity                 = "Infoviews.INFOMODE[BuildingUseEfficiencyElectricity]";
        public const string InfomodeTitleEfficiencyWater                       = "Infoviews.INFOMODE[BuildingUseEfficiencyWater]";
        public const string InfomodeTitleEfficiencySewage                      = "Infoviews.INFOMODE[BuildingUseEfficiencySewage]";
        public const string InfomodeTitleEfficiencyHealthcare                  = "Infoviews.INFOMODE[BuildingUseEfficiencyHealthcare]";
        public const string InfomodeTitleEfficiencyDeathcare                   = "Infoviews.INFOMODE[BuildingUseEfficiencyDeathcare]";
        public const string InfomodeTitleEfficiencyGarbageManagement           = "Infoviews.INFOMODE[BuildingUseEfficiencyGarbageManagement]";
        public const string InfomodeTitleEfficiencyEducation                   = "Infoviews.INFOMODE[BuildingUseEfficiencyEducation]";
        public const string InfomodeTitleEfficiencyResearch                    = "Infoviews.INFOMODE[BuildingUseEfficiencyResearch]";
        public const string InfomodeTitleEfficiencyFireRescue                  = "Infoviews.INFOMODE[BuildingUseEfficiencyFireRescue]";
        public const string InfomodeTitleEfficiencyDisasterControl             = "Infoviews.INFOMODE[BuildingUseEfficiencyDisasterControl]";
        public const string InfomodeTitleEfficiencyPolice                      = "Infoviews.INFOMODE[BuildingUseEfficiencyPolice]";
        public const string InfomodeTitleEfficiencyAdministration              = "Infoviews.INFOMODE[BuildingUseEfficiencyAdministration]";
        public const string InfomodeTitleEfficiencyTransportation              = "Infoviews.INFOMODE[BuildingUseEfficiencyTransportation]";
        public const string InfomodeTitleEfficiencyParkMaintenance             = "Infoviews.INFOMODE[BuildingUseEfficiencyParkMaintenance]";
        public const string InfomodeTitleEfficiencyParksRecreation             = "Infoviews.INFOMODE[BuildingUseEfficiencyParksRecreation]";
        public const string InfomodeTitleEfficiencyPost                        = "Infoviews.INFOMODE[BuildingUseEfficiencyPost]";
        public const string InfomodeTitleEfficiencyTelecom                     = "Infoviews.INFOMODE[BuildingUseEfficiencyTelecom]";
        public const string InfomodeTitleProcessingElectricityProduction       = "Infoviews.INFOMODE[BuildingUseProcessingElectricityProduction]";
        public const string InfomodeTitleProcessingWaterOutput                 = "Infoviews.INFOMODE[BuildingUseProcessingWaterOutput]";
        public const string InfomodeTitleProcessingSewageTreatment             = "Infoviews.INFOMODE[BuildingUseProcessingSewageTreatment]";
        public const string InfomodeTitleProcessingCrematoriumProcessing       = "Infoviews.INFOMODE[BuildingUseProcessingCrematoriumProcessing]";
        public const string InfomodeTitleProcessingGarbageProcessing           = "Infoviews.INFOMODE[BuildingUseProcessingGarbageProcessing]";
        public const string InfomodeTitleProcessingMailSortingSpeed            = "Infoviews.INFOMODE[BuildingUseProcessingMailSortingSpeed]";

        // Infomode tooltips.
        public const string InfomodeTooltipEmployeesResidential                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesResidential]";
        public const string InfomodeTooltipEmployeesCommercial                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesCommercial]";
        public const string InfomodeTooltipEmployeesIndustrial                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesIndustrial]";
        public const string InfomodeTooltipEmployeesOffice                     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesOffice]";
        public const string InfomodeTooltipEmployeesParking                    = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesParking]";
        public const string InfomodeTooltipEmployeesRoadMaintenance            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesRoadMaintenance]";
        public const string InfomodeTooltipEmployeesElectricity                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesElectricity]";
        public const string InfomodeTooltipEmployeesWater                      = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesWater]";
        public const string InfomodeTooltipEmployeesSewage                     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesSewage]";
        public const string InfomodeTooltipEmployeesHealthcare                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesHealthcare]";
        public const string InfomodeTooltipEmployeesDeathcare                  = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesDeathcare]";
        public const string InfomodeTooltipEmployeesGarbageManagement          = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesGarbageManagement]";
        public const string InfomodeTooltipEmployeesEducation                  = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesEducation]";
        public const string InfomodeTooltipEmployeesResearch                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesResearch]";
        public const string InfomodeTooltipEmployeesFireRescue                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesFireRescue]";
        public const string InfomodeTooltipEmployeesDisasterControl            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesDisasterControl]";
        public const string InfomodeTooltipEmployeesPolice                     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesPolice]";
        public const string InfomodeTooltipEmployeesAdministration             = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesAdministration]";
        public const string InfomodeTooltipEmployeesTransportation             = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesTransportation]";
        public const string InfomodeTooltipEmployeesParkMaintenance            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesParkMaintenance]";
        public const string InfomodeTooltipEmployeesParksRecreation            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesParksRecreation]";
        public const string InfomodeTooltipEmployeesPost                       = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesPost]";
        public const string InfomodeTooltipEmployeesTelecom                    = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEmployeesTelecom]";
        public const string InfomodeTooltipVisitorsHealthcare                  = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsHealthcare]";
        public const string InfomodeTooltipVisitorsCemetery                    = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsCemetery]";
        public const string InfomodeTooltipVisitorsCrematorium                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsCrematorium]";
        public const string InfomodeTooltipVisitorsElementarySchool            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsElementarySchool]";
        public const string InfomodeTooltipVisitorsHighSchool                  = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsHighSchool]";
        public const string InfomodeTooltipVisitorsCollege                     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsCollege]";
        public const string InfomodeTooltipVisitorsUniversity                  = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsUniversity]";
        public const string InfomodeTooltipVisitorsEmergencyShelter            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsEmergencyShelter]";
        public const string InfomodeTooltipVisitorsPoliceStation               = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsPoliceStation]";
        public const string InfomodeTooltipVisitorsPrison                      = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVisitorsPrison]";
        public const string InfomodeTooltipStorageCommercial                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageCommercial]";
        public const string InfomodeTooltipStorageIndustrial                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageIndustrial]";
        public const string InfomodeTooltipStorageOffice                       = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageOffice]";
        public const string InfomodeTooltipStorageBatteryCharge                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageBatteryCharge]";
        public const string InfomodeTooltipStoragePowerPlantFuel               = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStoragePowerPlantFuel]";
        public const string InfomodeTooltipStorageHealthcare                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageHealthcare]";
        public const string InfomodeTooltipStorageLandfill                     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageLandfill]";
        public const string InfomodeTooltipStorageGarbageManagement            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageGarbageManagement]";
        public const string InfomodeTooltipStorageEmergencyShelter             = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageEmergencyShelter]";
        public const string InfomodeTooltipStorageCargoTransportation          = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStorageCargoTransportation]";
        public const string InfomodeTooltipStoragePost                         = "Infoviews.INFOMODE_TOOLTIP[BuildingUseStoragePost]";
        public const string InfomodeTooltipVehiclesCommercialTruck             = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesCommercialTruck]";
        public const string InfomodeTooltipVehiclesIndustrialTruck             = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesIndustrialTruck]";
        public const string InfomodeTooltipVehiclesOfficeTruck                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesOfficeTruck]";
        public const string InfomodeTooltipVehiclesParked                      = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesParked]";
        public const string InfomodeTooltipVehiclesRoadMaintenance             = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesRoadMaintenance]";
        public const string InfomodeTooltipVehiclesAmbulance                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesAmbulance]";
        public const string InfomodeTooltipVehiclesMedicalHelicopter           = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesMedicalHelicopter]";
        public const string InfomodeTooltipVehiclesHearse                      = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesHearse]";
        public const string InfomodeTooltipVehiclesGarbageTruck                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesGarbageTruck]";
        public const string InfomodeTooltipVehiclesFireEngine                  = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesFireEngine]";
        public const string InfomodeTooltipVehiclesFireHelicopter              = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesFireHelicopter]";
        public const string InfomodeTooltipVehiclesDisasterResponse            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesDisasterResponse]";
        public const string InfomodeTooltipVehiclesEvacuationBus               = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesEvacuationBus]";
        public const string InfomodeTooltipVehiclesPoliceCar                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPoliceCar]";
        public const string InfomodeTooltipVehiclesPoliceHelicopter            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPoliceHelicopter]";
        public const string InfomodeTooltipVehiclesPrisonVan                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPrisonVan]";
        public const string InfomodeTooltipVehiclesBus                         = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesBus]";
        public const string InfomodeTooltipVehiclesTaxi                        = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesTaxi]";
        public const string InfomodeTooltipVehiclesTrain                       = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesTrain]";
        public const string InfomodeTooltipVehiclesTram                        = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesTram]";
        public const string InfomodeTooltipVehiclesSubway                      = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesSubway]";
        public const string InfomodeTooltipVehiclesParkMaintenance             = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesParkMaintenance]";
        public const string InfomodeTooltipVehiclesPost                        = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesPost]";
        public const string InfomodeTooltipVehiclesCargoStationTruck           = "Infoviews.INFOMODE_TOOLTIP[BuildingUseVehiclesCargoStationTruck]";
        public const string InfomodeTooltipEfficiencyResidential               = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyResidential]";
        public const string InfomodeTooltipEfficiencyCommercial                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyCommercial]";
        public const string InfomodeTooltipEfficiencyIndustrial                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyIndustrial]";
        public const string InfomodeTooltipEfficiencyOffice                    = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyOffice]";
        public const string InfomodeTooltipEfficiencyParking                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyParking]";
        public const string InfomodeTooltipEfficiencyRoadMaintenance           = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyRoadMaintenance]";
        public const string InfomodeTooltipEfficiencyElectricity               = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyElectricity]";
        public const string InfomodeTooltipEfficiencyWater                     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyWater]";
        public const string InfomodeTooltipEfficiencySewage                    = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencySewage]";
        public const string InfomodeTooltipEfficiencyHealthcare                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyHealthcare]";
        public const string InfomodeTooltipEfficiencyDeathcare                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyDeathcare]";
        public const string InfomodeTooltipEfficiencyGarbageManagement         = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyGarbageManagement]";
        public const string InfomodeTooltipEfficiencyEducation                 = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyEducation]";
        public const string InfomodeTooltipEfficiencyResearch                  = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyResearch]";
        public const string InfomodeTooltipEfficiencyFireRescue                = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyFireRescue]";
        public const string InfomodeTooltipEfficiencyDisasterControl           = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyDisasterControl]";
        public const string InfomodeTooltipEfficiencyPolice                    = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyPolice]";
        public const string InfomodeTooltipEfficiencyAdministration            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyAdministration]";
        public const string InfomodeTooltipEfficiencyTransportation            = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyTransportation]";
        public const string InfomodeTooltipEfficiencyParkMaintenance           = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyParkMaintenance]";
        public const string InfomodeTooltipEfficiencyParksRecreation           = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyParksRecreation]";
        public const string InfomodeTooltipEfficiencyPost                      = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyPost]";
        public const string InfomodeTooltipEfficiencyTelecom                   = "Infoviews.INFOMODE_TOOLTIP[BuildingUseEfficiencyTelecom]";
        public const string InfomodeTooltipProcessingElectricityProduction     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingElectricityProduction]";
        public const string InfomodeTooltipProcessingWaterOutput               = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingWaterOutput]";
        public const string InfomodeTooltipProcessingSewageTreatment           = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingSewageTreatment]";
        public const string InfomodeTooltipProcessingCrematoriumProcessing     = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingCrematoriumProcessing]";
        public const string InfomodeTooltipProcessingGarbageProcessing         = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingGarbageProcessing]";
        public const string InfomodeTooltipProcessingMailSortingSpeed          = "Infoviews.INFOMODE_TOOLTIP[BuildingUseProcessingMailSortingSpeed]";

        // District selector text.
        public const string EntireCity                                         = "BuildingUse.EntireCity";
        public const string DistrictSelectorTooltip                            = "BuildingUse.DistrictSelectorTooltip";

        // Select/deselect text.
        public const string SelectAll                                          = "BuildingUse.SelectAll";
        public const string DeselectAll                                        = "BuildingUse.DeselectAll";
        public const string SelectDeselectTooltip                              = "BuildingUse.SelectDeselectTooltip";

        // Vehicles in use/in maintenance text.
        public const string InUse                                              = "BuildingUse.InUse";
        public const string InMaintenance                                      = "BuildingUse.InMaintenance";
        public const string InUseInMaintenanceTooltip                          = "BuildingUse.InUseInMaintenanceTooltip";

        // Max color text.
        public const string MaxColor100Percent                                 = "BuildingUse.MaxColor100Percent";
        public const string MaxColor200Percent                                 = "BuildingUse.MaxColor200Percent";
        public const string MaxColorTooltip                                    = "BuildingUse.MaxColorTooltip";

        // Unit of measure text.
        public const string UnitOfMeasurePrefixKilo                            = "BuildingUse.UnitOfMeasurePrefixKilo";
        public const string UnitOfMeasurePrefixMega                            = "BuildingUse.UnitOfMeasurePrefixMega";
        public const string GigaWattHour                                       = "BuildingUse.GigaWattHour";

        // General text.
        public const string NoBuildings                                        = "BuildingUse.NoBuildings";

        // Settings.
        public const string SettingTitle                                       = "Options.SECTION[BuildingUse.BuildingUse.Mod]";
        public const string SettingGroupGeneral                                = "Options.GROUP[BuildingUse.BuildingUse.Mod.General]";
        public const string SettingZonedBuildingColorLabel                     = "Options.OPTION[BuildingUse.BuildingUse.Mod.ModSettings.ZonedBuildingColor]";
        public const string SettingZonedBuildingColorDesc                      = "Options.OPTION_DESCRIPTION[BuildingUse.BuildingUse.Mod.ModSettings.ZonedBuildingColor]";
        public const string SettingZonedBuildingColorChoiceThreeColors         = "Options.BuildingUse.BuildingUse.Mod.ZONEDBUILDINGCOLORCHOICE[ThreeColors]";
        public const string SettingZonedBuildingColorChoiceZoneColor           = "Options.BuildingUse.BuildingUse.Mod.ZONEDBUILDINGCOLORCHOICE[ZoneColor]";
        public const string SettingServiceBuildingColorLabel                   = "Options.OPTION[BuildingUse.BuildingUse.Mod.ModSettings.ServiceBuildingColor]";
        public const string SettingServiceBuildingColorDesc                    = "Options.OPTION_DESCRIPTION[BuildingUse.BuildingUse.Mod.ModSettings.ServiceBuildingColor]";
        public const string SettingServiceBuildingColorChoiceThreeColors       = "Options.BuildingUse.BuildingUse.Mod.SERVICEBUILDINGCOLORCHOICE[ThreeColors]";
        public const string SettingServiceBuildingColorChoiceRed               = "Options.BuildingUse.BuildingUse.Mod.SERVICEBUILDINGCOLORCHOICE[Red]";
        public const string SettingServiceBuildingColorChoiceVarious           = "Options.BuildingUse.BuildingUse.Mod.SERVICEBUILDINGCOLORCHOICE[Various]";
        public const string SettingColorSpecializedIndustryLotsLabel           = "Options.OPTION[BuildingUse.BuildingUse.Mod.ModSettings.ColorSpecializedIndustryLots]";
        public const string SettingColorSpecializedIndustryLotsDesc            = "Options.OPTION_DESCRIPTION[BuildingUse.BuildingUse.Mod.ModSettings.ColorSpecializedIndustryLots]";
        public const string SettingReverseColorsLabel                          = "Options.OPTION[BuildingUse.BuildingUse.Mod.ModSettings.ReverseColors]";
        public const string SettingReverseColorsDesc                           = "Options.OPTION_DESCRIPTION[BuildingUse.BuildingUse.Mod.ModSettings.ReverseColors]";
        public const string SettingGroupAbout                                  = "Options.GROUP[BuildingUse.BuildingUse.Mod.About]";
        public const string SettingModVersionLabel                             = "Options.OPTION[BuildingUse.BuildingUse.Mod.ModSettings.ModVersion]";
        public const string SettingModVersionDesc                              = "Options.OPTION_DESCRIPTION[BuildingUse.BuildingUse.Mod.ModSettings.ModVersion]";
    }
}
